everpsblog_admin_post:
  path: /everpsblog/post
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\PostController::indexAction'
    _legacy_controller: AdminEverPsBlogPost

everpsblog_admin_post_create:
  path: /everpsblog/post
  methods: [POST]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\PostController::createAction'
    _legacy_controller: AdminEverPsBlogPost

everpsblog_admin_post_update:
  path: /everpsblog/post/{postId}
  methods: [PUT]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\PostController::updateAction'
    _legacy_controller: AdminEverPsBlogPost
  requirements:
    postId: '\\d+'

everpsblog_admin_post_delete:
  path: /everpsblog/post/{postId}
  methods: [DELETE]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\PostController::deleteAction'
    _legacy_controller: AdminEverPsBlogPost
  requirements:
    postId: '\\d+'

everpsblog_admin_category:
  path: /everpsblog/category
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\CategoryController::indexAction'
    _legacy_controller: AdminEverPsBlogCategory

everpsblog_admin_tag:
  path: /everpsblog/tag
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\TagController::indexAction'
    _legacy_controller: AdminEverPsBlogTag

everpsblog_admin_author:
  path: /everpsblog/author
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\AuthorController::indexAction'
    _legacy_controller: AdminEverPsBlogAuthor

everpsblog_admin_comment:
  path: /everpsblog/comment
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\\Module\\Everpsblog\\Controller\\Admin\\CommentController::indexAction'
    _legacy_controller: AdminEverPsBlogComment
